\c miru_db;

INSERT INTO activity (user_id,name,description,street_address,city,state,zip_code,category,image) VALUES
(1,'XO World Project Sculpture','Consider checking out the XO World Project Sculpture located at the World Trade Center Campus. Designed by Daniel Anderson, the sculpture is a part of the “Share Love” movement to activate positivity, hope, and inclusiveness among people. The sculpture is made from 20,000 lbs of stainless steel and stands 12 ft. high by 24 ft. wide! It will be here for 2 years, so enjoy it while you can.','117 West St',' New York', 'NY', 10007,'Art','	https://findloveandtravel.com/wp-content/uploads/2020/03/XO-Word-Project-NYC.jpg'),
(1,'Staten Island Ferry','Did you say free transportation in NYC?! I know, shocking right! I guess they had to make it up somewhere for charging us locals over $15 USD to cross into Staten Island over the Verrazano Bridge.Anyways, so why would you even want to take a ride on this ferry you ask? Well because it’s the closest you will get to the Statue of Liberty for free!While on the ferry, you can stand in the front and back of the boat while in motion to get a really nice view of the Statue of Liberty and that stunning NYC Skyline.','79 N 11th St', 'Brooklyn', 'NY',11249,'Sightseeing','https://findloveandtravel.com/wp-content/uploads/2020/03/free-things-NYC-statue-of-liberty.jpg'),
(1,'Little Island NYC','All the hype has been around the new New York City Public Park, Little Island! This is a really unique and free public park because it is actually built on 132 pillars, making it an artificial island. The park is 2.4 acres and is located at Pier 55 on the Hudson.','Pier 55 at Hudson River Park Hudson River Greenway','New York', 'NY', 10014,'Parks','https://triptins.com/wp-content/uploads/2022/04/Pier-57-Rooftop-Park-Little-Island.jpeg.webp'),
(1,'The Flatiron Building','If architecture fascinates you, pay a visit to one of NYC’s most photographed buildings for its unique triangular shape splitting the streets. This 22 story building originally known as the Fuller Building opened in 1902.If architecture fascinates you, pay a visit to one of NYC’s most photographed buildings for its unique triangular shape splitting the streets. This 22 story building originally known as the Fuller Building opened in 1902.While you can’t officially go inside, you can snap a couple of photos, hang out in Madison Square Park, or even hit up Eataly for food heaven!','175 5th Ave', 'New York', 'NY', 10010,'Architecture','https://findloveandtravel.com/wp-content/uploads/2020/02/Flatiron-Building-Instagram-Spot.jpg'),
(1,'Soho NYC Murals','Soho happens to be one of my top 3 favorite neighborhoods in all of New York City! I worked in Soho for 2 years and the cute cobblestone streets, art, and shopping make it the perfect place to explore.If you are a Nespresso lover like me, they have a flagship store on Spring and Prince street, which is where I worked during my college days.','250 Mulberry St', 'New York', 'NY', 10012,'Art','https://findloveandtravel.com/wp-content/uploads/2020/03/bowery-wall.jpg'),
(1,'Bryant Park','If you love parks in urban spaces, make sure to add Bryant Park to your list! This green square is 9.6 acres and regularly holds free events during the Summer including movie screenings, exercise classes, and more!Oh, and during the holidays Bryant Park hosts the Bank of America Winter Village! This Winter Village offers free Ice skating in NYC (bring your own skates), a pop-up Christmas Market, tons of food vendors, and even Cozy Winter Igloos!','25 W 40th St','New York', 'NY', 10018,'Parks','https://findloveandtravel.com/wp-content/uploads/2019/12/Top-things-to-do-in-NYC-in-December-2.jpg'),
(2,'The Polonsky Exhibition','Hundreds of items have been pulled from the New York Public Library expansive and centuries-spanning archive to be put on display—many of them for the first time—in a permanent exhibition called The Polonsky Exhibition of The New York Public Library’s Treasures.Inside the NYPL Stephen A. Schwarzman Building and its beautiful Gottesman Hall, are more than 250 unique and rare items culled from its research centers: the Stephen A. Schwarzman Building, the Library for the Performing Arts and the Schomburg Center for Research in Black Culture.The exhibit, which opens to the public on Friday, September 24, spans 4,000 years of history and includes a wide range of history-making pieces, including the only surviving letter from Christoper Columbus announcing his discovery" of the Americas to King Ferdinand’s court and the first Gutenberg Bible brought over to the Americas.','476 5th Ave', 'New York', 'NY', 10018,'Art','https://media.timeout.com/images/105816631/1372/772/image.jpg'),
(2,'Gantry Plaza State Park','Not to be mistaken for Long Island, NY, I feel like Long Island City which is in Queens is often forgotten. Quite frankly, it is a shame because Long Island City (LIC) offers great restaurants, museums,  and one of my favorite parks, The Gantry Plaza State Park.This epic and free NYC park offers 12 acres of riverside views, green spaces, recreational spaces, and an incredible backdrop of Midtown Manhattan!  Make sure to see the giant Long Island sign and the Pepsi Cola sign while you are there!','4-09 47th Rd', 'Queens', 'NY', 10007,'Parks','	https://findloveandtravel.com/wp-content/uploads/2020/03/long-island-city-nyc-1.jpg'),
(2,'NYC Public Library','I’ve never been inside the NYC Public Library, but as a kid, I did once sit on the lion statues outside….. and then prompted to get down immediately! I do have a library card though!But if you love books and awesome architecture, the NYC Public Library should definitely be on your list of free things to do in NYC! It is still on my bucket list to visit inside.','135 E 46th St', 'New York', 'NY', 10017,'Sightseeing','https://findloveandtravel.com/wp-content/uploads/2020/03/new-york-public-library-nyc.jpg'),
(2,'The Vessel','Starting with NYC’s newest attraction, The Vessel! Located in the Hudson Yards, the Vessel is easily one of the best free things to do during your visit to NYC.','20 Hudson Yards','New York','NY',10001,'Architecture','https://upload.wikimedia.org/wikipedia/commons/f/f6/Hudson_Yards_Plaza_March_2019_53.jpg'),
(2,'The Highline','Make your way to the Chelsea Highline. This iconic railway turned greenway is one of my all-time favorite places to visit, especially on a nice sunny day!','-','New York','NY',10011,'Sightseeing','https://upload.wikimedia.org/wikipedia/commons/5/56/AHigh_Line_Park%2C_Section_1a.jpg'),
(2,'Central Park','Central Park is a staple for NYC and luckily for all of us, it’s among one of the many free things to do!','3234 5th Ave','New York','NY',10075,'Parks','https://media-cdn.tripadvisor.com/media/photo-s/0e/16/1a/e6/new-york-city-central.jpg'),
(3,'Chrysler Building','One of the coolest Sky Scrappers IMO goes to the Chrysler Building. This gem of a building stands at 1,046 ft high from the antenna spire and is the world’s tallest brick building with steelwork! The building was completed in a little less than 2 years opening up in 1930.The Chrysler Buiding is the 11th tallest skyscraper in NYC and it can be found on lists of favorite architecture due to its unique art deco style. So why should you care? Because besides seeing it in the famous NYC skyline, you can also visit the lobby for free.','405 Lexington Ave', 'New York', 'NY', 10174,'Architecture','https://findloveandtravel.com/wp-content/uploads/2020/06/New-York-Streets.jpg'),
(3,'Grand Central Station','Grand Central Station is probably one of the prettiest subway stations in NYC. Who knew a train station could be NYC must-do on your itinerary?!Besides being the backdrop of more movies than I can count, the ceiling art is stunning, and it’s a great place to people watch. While inside, you will find restaurants, a farmers market, the whispering walls, and shopping.  After hanging out at Grand Central, you can take the S line right into Times Square, win, win!','89 E 42nd St','New York', 'NY', 10017,'Architecture','https://findloveandtravel.com/wp-content/uploads/2021/11/grand-central-terminal-nyc.jpg'),
(3,'Times Square','Did you even visit NYC without walking through Times Square? This is easily one of the top things to do in NYC especially for first-timers that of course, is also free.With huge billboards, the M&M store (yum), the naked cowboy, people doing street performances, it’s definitely an interesting place to experience, to say the least!','-','New York','NY',10036,'Sightseeing','https://findloveandtravel.com/wp-content/uploads/2020/02/time-squre-new-york.jpg'),
(3,'Washington Square Park','Washington Square Park is another one of my favorite places to hang in the city, especially on a Spring or Summer day.Head here to hang around the fountain, people watch, eat a snack, and view the Washington Square Arch. During the Summer, they also hold different free activities you can check for!','Washington Square N', 'New York', 'NY', 10012,'Parks','https://findloveandtravel.com/wp-content/uploads/2020/03/washington-sq-park-fountain.jpg'),
(3,'Flushing Meadows Corona Park','Another excellent and free park to visit in NYC is the Flushing Medows Park! You might remember this park from the Movie Men and Black with the two observation towers! Located in Flushing, Queens, it is also the 4th largest park in NYC! The park is also widely known as the home of the 1939 and 1964 Wold Fair! Additionally, if you visit during the spring, you will have the opportunity to see some really beautiful cherry blossoms!','Between Grand Central Pkwy and Van Wyck Expy','Queens','NY', 11354,'Parks','https://findloveandtravel.com/wp-content/uploads/2020/02/queens-ny-cherry-blossom.jpg'),
(3,'Spirit Of The City Instalition','Created by MINI and the London-based practice United Visual Artists, "Spirit Of The City" is an installation in the Greenpoint creative space A/D/O. Probing the physical and emotional response individuals experience when navigating urban environments, the installation is a sequence of mirrors that not only reflects the people around it but also changes according to the lighting and shadows of the day. On view until September 2nd.','29 Norman Ave', 'Brooklyn', 'NY', 11222,'Art','https://www.designgallerist.com/blog/wp-content/uploads/2018/06/Ddd2pJ2V4AAPIWG.jpg'),
(4,'Rockefeller Center','Rockefeller Center is one of my all-time favorite places to visit in NYC during the holidays, but it’s still great all season long. Around the area are tons of food spots, Radio City Music Hall, Saint Patricks Cathedral, and a stroll down 5th Ave to all the high-end designer stores.If your budget does allow it, I would recommend getting tickets for visiting the Top of the Rock. This is easily one of the best observation decks in NYC and is located at Rockefeller Plaza. If you do plan on doing a lot of paid attractions, your best bet will probably be an NYC Sightseeing Pass – will cover below!','45 Rockefeller Plaza', 'New York', 'NY', 10111,'Sightseeing','https://findloveandtravel.com/wp-content/uploads/2019/12/Top-things-to-do-in-NYC-in-December-8.jpg'),
(4,'The Oculus','The Oculus is a part of the new World Trade Center Transportation hub that acts as both a mall and subway station. This architectural gem was designed by Santiago Calatrava.Make sure to check out the Oculus from both the inside and outside since both are very picturesque! They often have a farmers market inside the Oculus along with a Christmas Market during the holidays. It is also a part of a larger shopping hub with tons of stores.','Church St', 'New York', 'NY', 10006,'Architecture','https://findloveandtravel.com/wp-content/uploads/2021/11/the-oculus-nyc.jpg'),
(4,'The Brooklyn Bridge','Make your way to the famous Brooklyn Bridge and cross over to DUMBO Down Under Manhattan Bridge Overpass, Brooklyn. The bridge spans 1.1 miles and was once the largest suspension bridge.When the bridge originally opened, it actually wasn’t a free NYC activity to do. It cost a penny to cross by foot, and 5 cents by horse and carriage.Thankfully, we can add crossing the Brooklyn Bridge to one of the many awesome free things to do in NYC now! When crossing the Bridge, you will also be treated to fantastic views of Manhattan!','Brooklyn Bridge','New York','NY',10038,'Sightseeing','https://findloveandtravel.com/wp-content/uploads/2020/02/brooklyn-bridge.jpg'),
(4,'Brooklyn Bridge Park','After crossing the bridge, hang out in Dumbo around Brooklyn Bridge Park. The park/pier is especially nice during the Spring/ Summer where you will find people out picnicking on the lawns, and further down roller skating, enjoying Jane’s Carousel, playing basketball, and more.From the walkway, you can even see the Statue of Liberty from a “very” far.','334 Furman St', 'Brooklyn', 'NY', 11201,'Parks','https://findloveandtravel.com/wp-content/uploads/2020/02/Dumbo-NYC-Instagram-Spot.jpg'),
(4,'Coney Island Boardwalk','This can’t be a full list of free things to do in NYC without adding the famed Coney Island Boardwalk. It is especially nice to visit during the spring/summer when the weather is nice. You can enjoy getting some sun at the beach and people watch some really interesting characters! If this is your first time in New York and you are pressed for time, I would leave this one out, however.','1000 Surf Ave', 'Brooklyn', 'NY', 11224,'Parks','https://findloveandtravel.com/wp-content/uploads/2022/03/Coney-island-nyc-brooklyn-at-night.jpg');


INSERT INTO comments (activity_id,name,comment) VALUES 
(1, 'Rose','I don’t like this place. Way too many tourists'),
(2, 'Younes','Never been, but definitely on my to do list'),
(3, 'JJ','I love it. It’s super relaxing, especially if you find the nooks and craanies'), 
(3, 'Sev','People watching is the best here and free!');

INSERT INTO users (name,email,password) VALUES 
('Younes Tahiri', 'ytahiri82@gmail.com', '$2b$10$eIZ/CGUjwHzbXeJBFtxUBeMG1duAglPNF/lzMKjfKSigDEJb..R.6')


	

    
